// <auto-generated />
using System;
using FlyToHappy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlyToHappy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907205437_SeedDemoFlights")]
    partial class SeedDemoFlights
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlyToHappy.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaggageKg")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CabinBaggageIncluded")
                        .HasColumnType("bit");

                    b.Property<string>("CabinClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CheckedBaggageIncluded")
                        .HasColumnType("bit");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stops")
                        .HasColumnType("int");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            Airline = "Turkish Airlines",
                            AirlineCode = "TK",
                            ArrivalAirport = "FCO",
                            ArrivalTime = "09:55",
                            BaggageKg = 23,
                            BasePrice = 2490m,
                            CabinBaggageIncluded = true,
                            CabinClass = "Ekonomi",
                            CheckedBaggageIncluded = true,
                            DepartureAirport = "IST",
                            DepartureTime = "08:10",
                            Duration = "2 sa 45 dk",
                            FlightNumber = "TK1861",
                            Price = 2490m,
                            Stops = 0
                        },
                        new
                        {
                            FlightId = 2,
                            Airline = "AJet",
                            AirlineCode = "VF",
                            ArrivalAirport = "FCO",
                            ArrivalTime = "11:10",
                            BaggageKg = 20,
                            BasePrice = 1940m,
                            CabinBaggageIncluded = true,
                            CabinClass = "Ekonomi",
                            CheckedBaggageIncluded = true,
                            DepartureAirport = "IST",
                            DepartureTime = "09:30",
                            Duration = "2 sa 40 dk",
                            FlightNumber = "VF1306",
                            Price = 1940m,
                            Stops = 0
                        },
                        new
                        {
                            FlightId = 3,
                            Airline = "Pegasus",
                            AirlineCode = "PC",
                            ArrivalAirport = "FCO",
                            ArrivalTime = "11:20",
                            BaggageKg = 15,
                            BasePrice = 1690m,
                            CabinBaggageIncluded = true,
                            CabinClass = "Ekonomi",
                            CheckedBaggageIncluded = false,
                            DepartureAirport = "IST",
                            DepartureTime = "05:40",
                            Duration = "6 sa 40 dk",
                            FlightNumber = "PC1248",
                            Price = 1690m,
                            Stops = 1
                        },
                        new
                        {
                            FlightId = 4,
                            Airline = "Pegasus",
                            AirlineCode = "PC",
                            ArrivalAirport = "FCO",
                            ArrivalTime = "08:20",
                            BaggageKg = 15,
                            BasePrice = 1850m,
                            CabinBaggageIncluded = true,
                            CabinClass = "Ekonomi",
                            CheckedBaggageIncluded = false,
                            DepartureAirport = "IST",
                            DepartureTime = "06:25",
                            Duration = "2 sa 55 dk",
                            FlightNumber = "PC1242",
                            Price = 1850m,
                            Stops = 0
                        },
                        new
                        {
                            FlightId = 5,
                            Airline = "AJet",
                            AirlineCode = "VF",
                            ArrivalAirport = "FCO",
                            ArrivalTime = "13:55",
                            BaggageKg = 20,
                            BasePrice = 1790m,
                            CabinBaggageIncluded = true,
                            CabinClass = "Ekonomi",
                            CheckedBaggageIncluded = true,
                            DepartureAirport = "IST",
                            DepartureTime = "12:05",
                            Duration = "2 sa 50 dk",
                            FlightNumber = "VF1312",
                            Price = 1790m,
                            Stops = 0
                        },
                        new
                        {
                            FlightId = 6,
                            Airline = "Pegasus",
                            AirlineCode = "PC",
                            ArrivalAirport = "FCO",
                            ArrivalTime = "17:15",
                            BaggageKg = 20,
                            BasePrice = 2090m,
                            CabinBaggageIncluded = true,
                            CabinClass = "Ekonomi",
                            CheckedBaggageIncluded = true,
                            DepartureAirport = "IST",
                            DepartureTime = "15:15",
                            Duration = "3 saat",
                            FlightNumber = "PC1256",
                            Price = 2090m,
                            Stops = 0
                        },
                        new
                        {
                            FlightId = 7,
                            Airline = "AJet",
                            AirlineCode = "VF",
                            ArrivalAirport = "FCO",
                            ArrivalTime = "23:15",
                            BaggageKg = 20,
                            BasePrice = 2150m,
                            CabinBaggageIncluded = true,
                            CabinClass = "Ekonomi",
                            CheckedBaggageIncluded = false,
                            DepartureAirport = "IST",
                            DepartureTime = "21:20",
                            Duration = "2 sa 55 dk",
                            FlightNumber = "VF1318",
                            Price = 2150m,
                            Stops = 0
                        },
                        new
                        {
                            FlightId = 8,
                            Airline = "Pegasus",
                            AirlineCode = "PC",
                            ArrivalAirport = "FCO",
                            ArrivalTime = "22:05",
                            BaggageKg = 15,
                            BasePrice = 2290m,
                            CabinBaggageIncluded = true,
                            CabinClass = "Ekonomi",
                            CheckedBaggageIncluded = false,
                            DepartureAirport = "IST",
                            DepartureTime = "16:40",
                            Duration = "6 sa 25 dk",
                            FlightNumber = "PC1260",
                            Price = 2290m,
                            Stops = 1
                        },
                        new
                        {
                            FlightId = 9,
                            Airline = "Turkish Airlines",
                            AirlineCode = "TK",
                            ArrivalAirport = "FCO",
                            ArrivalTime = "20:55",
                            BaggageKg = 23,
                            BasePrice = 2390m,
                            CabinBaggageIncluded = true,
                            CabinClass = "Ekonomi",
                            CheckedBaggageIncluded = true,
                            DepartureAirport = "IST",
                            DepartureTime = "19:05",
                            Duration = "2 sa 50 dk",
                            FlightNumber = "TK1863",
                            Price = 2390m,
                            Stops = 0
                        },
                        new
                        {
                            FlightId = 10,
                            Airline = "Turkish Airlines",
                            AirlineCode = "TK",
                            ArrivalAirport = "FCO",
                            ArrivalTime = "15:30",
                            BaggageKg = 23,
                            BasePrice = 2650m,
                            CabinBaggageIncluded = true,
                            CabinClass = "Ekonomi",
                            CheckedBaggageIncluded = true,
                            DepartureAirport = "IST",
                            DepartureTime = "13:40",
                            Duration = "2 sa 50 dk",
                            FlightNumber = "TK1867",
                            Price = 2650m,
                            Stops = 0
                        });
                });

            modelBuilder.Entity("FlyToHappy.Models.Passenger", b =>
                {
                    b.Property<Guid>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPassport")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotTurkishCitizen")
                        .HasColumnType("bit");

                    b.Property<string>("PassengerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("PassportExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PassengerId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("FlyToHappy.Models.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<string>("Cabin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChargeablePassengers")
                        .HasColumnType("int");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<int>("DepartureFlightId")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Infants")
                        .HasColumnType("int");

                    b.Property<string>("Pnr")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<int?>("ReturnFlightId")
                        .HasColumnType("int");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPassengers")
                        .HasColumnType("int");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservationId");

                    b.HasIndex("DepartureFlightId");

                    b.HasIndex("Pnr")
                        .IsUnique();

                    b.HasIndex("ReturnFlightId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("FlyToHappy.Models.Passenger", b =>
                {
                    b.HasOne("FlyToHappy.Models.Reservation", "Reservation")
                        .WithMany("Passengers")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("FlyToHappy.Models.Reservation", b =>
                {
                    b.HasOne("FlyToHappy.Models.Flight", "DepartureFlight")
                        .WithMany()
                        .HasForeignKey("DepartureFlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlyToHappy.Models.Flight", "ReturnFlight")
                        .WithMany()
                        .HasForeignKey("ReturnFlightId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("FlyToHappy.Models.BaggageSelection", "BaggageSelection", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("TotalBaggagePrice")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");

                            b1.OwnsOne("FlyToHappy.Models.BaggageOption", "CabinBaggage", b2 =>
                                {
                                    b2.Property<Guid>("BaggageSelectionReservationId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Kg")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<decimal>("Price")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("Type")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("BaggageSelectionReservationId");

                                    b2.ToTable("Reservations");

                                    b2.WithOwner()
                                        .HasForeignKey("BaggageSelectionReservationId");
                                });

                            b1.OwnsOne("FlyToHappy.Models.BaggageOption", "CheckedBaggage", b2 =>
                                {
                                    b2.Property<Guid>("BaggageSelectionReservationId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Kg")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<decimal>("Price")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("Type")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("BaggageSelectionReservationId");

                                    b2.ToTable("Reservations");

                                    b2.WithOwner()
                                        .HasForeignKey("BaggageSelectionReservationId");
                                });

                            b1.Navigation("CabinBaggage")
                                .IsRequired();

                            b1.Navigation("CheckedBaggage")
                                .IsRequired();
                        });

                    b.OwnsOne("FlyToHappy.Models.BookingPriceSummary", "PriceSummary", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("BaggagePrice")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("CabinBaggagePrice")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("CheckedBaggagePrice")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("DepartureFlightPrice")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ReturnFlightPrice")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("TotalPrice")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.Navigation("BaggageSelection")
                        .IsRequired();

                    b.Navigation("DepartureFlight");

                    b.Navigation("PriceSummary")
                        .IsRequired();

                    b.Navigation("ReturnFlight");
                });

            modelBuilder.Entity("FlyToHappy.Models.Reservation", b =>
                {
                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
